name: ui_task_assignments
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  get_it: ^7.6.7
  http: ^1.2.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
